server:
  port: 88
spring:
  application:
    name: note-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin_route
#          因为gateway 无法解析下划线, 所以一定记着，微服务下给服务起实例名不要带下划线
          uri: lb://note-admin
          predicates:
            - Path=/api/admin/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}



    #        #nginx负载均衡
#        - id: admin_host_route
#          uri: lb://note_admin
#          predicates:
#            - Host=admin.note.com


