server:
  port: 9000
spring:
  application:
    name: note-search
  cloud:
    nacos:
      server-addr: 192.168.56.10:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    # convertToNull 解决 com.mysql.cj.exceptions.DataReadException: Zero date value prohibited
    url: jdbc:mysql://192.168.56.10:3306/canal_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: ppppp.evernote.mapper # 注意：对应实体类的路径
  # 配置主键自增策略   按照数据库的来
  global-config:
    db-config:
      id-type: auto
